# Generated by Django 5.1rc1 on 2024-08-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedrijf',
            name='id',
        ),
        migrations.AlterField(
            model_name='bedrijf',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
