# Generated by Django 5.1rc1 on 2024-08-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_bedrijf_id_alter_bedrijf_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedrijf',
            name='popularity',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
