# Generated by Django 5.1rc1 on 2024-08-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bedrijf_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedrijf',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
