# Generated by Django 5.1rc1 on 2024-08-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_bedrijf_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedrijf',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bedrijf',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
